// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1807.Redbird.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc1807.Redbird.Robot;
import org.usfirst.frc1807.Redbird.RobotMap;

/**
 *
 */
public class elevator_up extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_height;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public elevator_up(double height) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_height = height;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	while(RobotMap.elevatorpot.get() <=.86 && Robot.oi.manip.getRawButton(5)) {
    		RobotMap.elevatorelevator_one.set( (Math.sqrt((RobotMap.elevatorpot.get()-.86)/-.672)+.2) * 1.5 + .12);
    		
    		RobotMap.elevatorelevator_two.set( (Math.sqrt((RobotMap.elevatorpot.get()-.86)/-.672)+.2) * 1.5 + .12);
        	
        	SmartDashboard.putNumber("pottieee: ", RobotMap.elevatorpot.get());
        	SmartDashboard.putNumber("speed rn: ", 1);
    	}
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        if(RobotMap.elevatorpot.get() >=.86) {
        	return true;
        } else if(!Robot.oi.manip.getRawButton(5)) {
        	return true;
        } else {
        	return false;
        }
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
